In [1]:
import os
os.chdir('D:\Engr Course\VSCode\ML')

In [2]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, explained_variance_score, r2_score
from timeseires.utils.to_split import to_split
from timeseires.utils.multivariate_multi_step import multivariate_multi_step
from timeseires.utils.multivariate_single_step import multivariate_single_step
from timeseires.utils.univariate_multi_step import univariate_multi_step
from timeseires.utils.univariate_single_step import univariate_single_step
from timeseires.utils.CosineAnnealingLRS import CosineAnnealingLRS
from timeseires.callbacks.EpochCheckpoint import EpochCheckpoint
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.models import load_model
from tensorflow.keras.layers import LSTM, Bidirectional, Add
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import Conv1D,TimeDistributed
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten,MaxPooling1D,Concatenate,AveragePooling1D, GlobalMaxPooling1D, Input
from tensorflow.keras.models import Sequential,Model
import pandas as pd
import time, pickle
import numpy as np
import tensorflow.keras.backend as K
import tensorflow
from tensorflow.keras.layers import Input, Reshape, Lambda
from tensorflow.keras.layers import Layer, Flatten, LeakyReLU, concatenate, Dense
from tensorflow.keras.regularizers import l2
import glob
import h5py
import matplotlib.pyplot as plt
from keras.callbacks import Callback

In [3]:
#lookback = 24
model = None
start_epoch = 0
time_steps=24
num_features=21

In [4]:
def MLP():
    model = Sequential()
    model.add(Flatten(input_shape=(time_steps , num_features)))
    model.add(Dense(32, activation='relu'))
    model.add(Dense(1))
    return model

In [5]:
model1 = MLP()
model1.summary()

d:\Engr Course\VSCode\ML\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten (Flatten)               │ (None, 504)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 32)             │        16,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 16,193 (63.25 KB)

 Trainable params: 16,193 (63.25 KB)

 Non-trainable params: 0 (0.00 B)

In [8]:
tensorflow.keras.utils.plot_model(model1 )

You must install graphviz (see instructions at https://graphviz.gitlab.io/download/) for `plot_model` to work.


In [9]:
checkpoints = r'C:\Users\swiss\Desktop\ML\Lab 7\E1\E1-cp-{epoch:04d}-loss{val_loss:.2f}.h5'
OUTPUT_PATH = r'C:\Users\swiss\Desktop\ML\Lab 7\E1'
#FIG_PATH = os.path.sep.join([OUTPUT_PATH,"\history.png"])
#JSON_PATH = os.path.sep.join([OUTPUT_PATH,"\history.json"])

In [10]:
# construct the callback to save only the *best* model to disk
# based on the validation loss
EpochCheckpoint1 = ModelCheckpoint(checkpoints,
                             monitor="val_loss",
                             save_best_only=True, 
                             verbose=1)
#TrainingMonitor1=TrainingMonitor(FIG_PATH, jsonPath=JSON_PATH, startAt=start_epoch)

# construct the set of callbacks
callbacks = [EpochCheckpoint1]

In [11]:
# if there is no specific model checkpoint supplied, then initialize
# the network and compile the model
if model is None:
    print("[INFO] compiling model...")
    model =MLP()
    opt = Adam(1e-3)
    model.compile(loss= 'mae', optimizer=opt, metrics=["mae", "mape"])
# otherwise, load the checkpoint from disk
else:
    print("[INFO] loading {}...".format(model))
    model = load_model(model)

    # update the learning rate
    print("[INFO] old learning rate: {}".format(K.get_value(model.optimizer.lr)))
    K.set_value(model.optimizer.lr, 1e-4)
    print("[INFO] new learning rate: {}".format(K.get_value(model.optimizer.lr)))

[INFO] compiling model...


In [12]:
import os
path_dataset =r'C:\Users\swiss\Desktop\ML\Lab 7'
path_tr = os.path.join(path_dataset, 'AEP_train.csv')
df_tr = pd.read_csv(path_tr)
train_set = df_tr.iloc[:].values
path_v = os.path.join(path_dataset, 'AEP_validation.csv')
df_v = pd.read_csv(path_v)
validation_set = df_v.iloc[:].values 
path_te = os.path.join(path_dataset, 'AEP_test.csv')
df_te = pd.read_csv(path_te)
test_set = df_te.iloc[:].values 

path_scaler = os.path.join(path_dataset, 'AEP_Scaler.pkl')
scaler         = pickle.load(open(path_scaler, 'rb'))

train_set.shape, validation_set.shape, test_set.shape

d:\Engr Course\VSCode\ML\Lib\site-packages\sklearn\base.py:380: InconsistentVersionWarning: Trying to unpickle estimator MinMaxScaler from version 1.0.2 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(


((84907, 21), (24259, 21), (12130, 21))

In [13]:
df_te.head(1)

aep  Is_holiday1  Is_holiday2  Is_Weekend1  Is_Weekend2  sin_month  \
0  0.518532          1.0          0.0          1.0          0.0        1.0   

      cos_month  sin_week  cos_week  sin_hour  ...  sin_wintert  cos_wintert  \
0  6.123234e-17  0.866025      -0.5 -0.707107  ...          0.0          1.0   

   sin_springt   cos_springt  sin_summert  cos_summert  sin_fallt  cos_fallt  \
0          1.0  6.123234e-17          0.0          1.0        0.0        1.0   

   sin_year_dayt  cos_year_dayt  
0       0.956235         0.2926  

[1 rows x 21 columns]

In [14]:
test_set[0]

array([ 5.18532385e-01,  1.00000000e+00,  0.00000000e+00,  1.00000000e+00,
        0.00000000e+00,  1.00000000e+00,  6.12323400e-17,  8.66025404e-01,
       -5.00000000e-01, -7.07106781e-01, -7.07106781e-01,  0.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  6.12323400e-17,  0.00000000e+00,
        1.00000000e+00,  0.00000000e+00,  1.00000000e+00,  9.56234827e-01,
        2.92600336e-01])

In [15]:
time_steps=2
num_features=21

In [16]:
train_X , train_y = univariate_multi_step(train_set, time_steps, target_col=0,target_len=0)

In [17]:
train_X[0]

array([[ 1.69100212e-01,  1.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00, -8.66025404e-01,
         5.00000000e-01, -8.66025404e-01, -5.00000000e-01,
         2.58819045e-01,  9.65925826e-01,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         6.12323400e-17, -9.99768502e-01,  2.15160974e-02],
       [ 1.41395233e-01,  1.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00, -8.66025404e-01,
         5.00000000e-01, -8.66025404e-01, -5.00000000e-01,
         5.00000000e-01,  8.66025404e-01,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         6.12323400e-17, -9.99768502e-01,  2.15160974e-02]])

In [18]:
train_y[0]

array([], dtype=float64)

In [19]:
time_steps =24
train_X , train_y = univariate_multi_step(train_set, time_steps, target_col=1,target_len=2)

In [20]:
train_X[0]

array([[ 1.69100212e-01,  1.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00, -8.66025404e-01,
         5.00000000e-01, -8.66025404e-01, -5.00000000e-01,
         2.58819045e-01,  9.65925826e-01,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         6.12323400e-17, -9.99768502e-01,  2.15160974e-02],
       [ 1.41395233e-01,  1.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00, -8.66025404e-01,
         5.00000000e-01, -8.66025404e-01, -5.00000000e-01,
         5.00000000e-01,  8.66025404e-01,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         6.12323400e-17, -9.99768502e-01,  2.15160974e-02],
       [ 1.26232372e-01,  1.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00, -8.66025404e-01,
         5.00000000e-01, -8.66025404e-01, -5.00000000e

In [21]:
train_y[0]

array([1., 1.])

In [22]:
start = time.time()
train_X , train_y = univariate_multi_step(train_set, time_steps, target_col=0,target_len=1)
validation_X, validation_y = univariate_multi_step(validation_set, time_steps, target_col=0,target_len=1)
test_X, test_y = univariate_multi_step(test_set, time_steps, target_col=0,target_len=1)
print('Time Consumed', time.time()-start, "sec")

Time Consumed 0.8664641380310059 sec


In [23]:
epochs = 10
verbose = 1 #0
batch_size = 32
History = model.fit(train_X,
                        train_y,
                        batch_size=batch_size,   
                        epochs = epochs, 
                        validation_data = (validation_X,validation_y),
                        callbacks=callbacks,
                    verbose = verbose)

Epoch 1/10
2636/2653 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0836 - mae: 0.0836 - mape: 189.5059
Epoch 1: val_loss improved from inf to 0.02718, saving model to C:\Users\swiss\Desktop\ML\Lab 7\E1\E1-cp-0001-loss0.03.h5


2653/2653 ━━━━━━━━━━━━━━━━━━━━ 21s 4ms/step - loss: 0.0834 - mae: 0.0834 - mape: 191.3735 - val_loss: 0.0272 - val_mae: 0.0272 - val_mape: 11.3083
Epoch 2/10
2638/2653 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0275 - mae: 0.0275 - mape: 69.9652
Epoch 2: val_loss improved from 0.02718 to 0.01953, saving model to C:\Users\swiss\Desktop\ML\Lab 7\E1\E1-cp-0002-loss0.02.h5


2653/2653 ━━━━━━━━━━━━━━━━━━━━ 17s 4ms/step - loss: 0.0275 - mae: 0.0275 - mape: 72.0127 - val_loss: 0.0195 - val_mae: 0.0195 - val_mape: 7.6919
Epoch 3/10
2643/2653 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0231 - mae: 0.0231 - mape: 1399.2329
Epoch 3: val_loss did not improve from 0.01953
2653/2653 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 0.0231 - mae: 0.0231 - mape: 1395.5673 - val_loss: 0.0209 - val_mae: 0.0209 - val_mape: 9.0440
Epoch 4/10
2640/2653 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0203 - mae: 0.0203 - mape: 56.1804
Epoch 4: val_loss improved from 0.01953 to 0.01949, saving model to C:\Users\swiss\Desktop\ML\Lab 7\E1\E1-cp-0004-loss0.02.h5


2653/2653 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 0.0203 - mae: 0.0203 - mape: 56.3824 - val_loss: 0.0195 - val_mae: 0.0195 - val_mape: 8.7667
Epoch 5/10
2645/2653 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0190 - mae: 0.0190 - mape: 379.3162
Epoch 5: val_loss did not improve from 0.01949
2653/2653 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 0.0190 - mae: 0.0190 - mape: 378.9845 - val_loss: 0.0246 - val_mae: 0.0246 - val_mape: 11.4874
Epoch 6/10
2640/2653 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0183 - mae: 0.0183 - mape: 234.4966
Epoch 6: val_loss improved from 0.01949 to 0.01826, saving model to C:\Users\swiss\Desktop\ML\Lab 7\E1\E1-cp-0006-loss0.02.h5


2653/2653 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 0.0183 - mae: 0.0183 - mape: 234.1854 - val_loss: 0.0183 - val_mae: 0.0183 - val_mape: 8.3898
Epoch 7/10
2651/2653 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0171 - mae: 0.0171 - mape: 634.2338
Epoch 7: val_loss improved from 0.01826 to 0.01649, saving model to C:\Users\swiss\Desktop\ML\Lab 7\E1\E1-cp-0007-loss0.02.h5


2653/2653 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 0.0171 - mae: 0.0171 - mape: 633.9594 - val_loss: 0.0165 - val_mae: 0.0165 - val_mape: 7.8699
Epoch 8/10
2647/2653 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0163 - mae: 0.0163 - mape: 695.1567
Epoch 8: val_loss did not improve from 0.01649
2653/2653 ━━━━━━━━━━━━━━━━━━━━ 19s 4ms/step - loss: 0.0163 - mae: 0.0163 - mape: 694.6329 - val_loss: 0.0179 - val_mae: 0.0179 - val_mape: 7.9455
Epoch 9/10
2638/2653 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0162 - mae: 0.0162 - mape: 846.6962
Epoch 9: val_loss did not improve from 0.01649
2653/2653 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 0.0162 - mae: 0.0162 - mape: 844.4225 - val_loss: 0.0217 - val_mae: 0.0217 - val_mape: 9.1172
Epoch 10/10
2643/2653 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0160 - mae: 0.0160 - mape: 33.8007
Epoch 10: val_loss improved from 0.01649 to 0.01630, saving model to C:\Users\swiss\Desktop\ML\Lab 7\E1\E1-cp-0010-loss0.02.h5


2653/2653 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 0.0160 - mae: 0.0160 - mape: 35.4416 - val_loss: 0.0163 - val_mae: 0.0163 - val_mape: 7.2808


In [41]:
from tensorflow.keras.models import load_model
from tensorflow.keras.losses import MeanAbsoluteError

model = load_model(
    r'C:\Users\swiss\Desktop\ML\Lab 7\E1\E1-cp-0009-loss0.01.h5',
    custom_objects={'mae': MeanAbsoluteError()}
)
y_pred_scaled   = model.predict(test_X)
y_pred          = scaler.inverse_transform(y_pred_scaled)
y_test_unscaled = scaler.inverse_transform(test_y)
# Mean Absolute Error (MAE)
MAE = np.mean(abs(y_pred - y_test_unscaled)) 
print('Mean Absolute Error (MAE): ' + str(np.round(MAE, 2)))

# Median Absolute Error (MedAE)
MEDAE = np.median(abs(y_pred - y_test_unscaled))
print('Median Absolute Error (MedAE): ' + str(np.round(MEDAE, 2)))

# Mean Squared Error (MSE)
MSE = np.square(np.subtract(y_pred, y_test_unscaled)).mean()
print('Mean Squared Error (MSE): ' + str(np.round(MSE, 2)))

# Root Mean Squarred Error (RMSE) 
RMSE = np.sqrt(np.mean(np.square(y_pred - y_test_unscaled)))
print('Root Mean Squared Error (RMSE): ' + str(np.round(RMSE, 2)))

# Mean Absolute Percentage Error (MAPE)
MAPE = np.mean((np.abs(np.subtract(y_test_unscaled, y_pred)/ y_test_unscaled))) * 100
print('Mean Absolute Percentage Error (MAPE): ' + str(np.round(MAPE, 2)) + ' %')

# Median Absolute Percentage Error (MDAPE)
MDAPE = np.median((np.abs(np.subtract(y_test_unscaled, y_pred)/ y_test_unscaled))) * 100
print('Median Absolute Percentage Error (MDAPE): ' + str(np.round(MDAPE, 2)) + ' %')

print('\n\ny_test_unscaled.shape= ',y_test_unscaled.shape)
print('y_pred.shape= ',y_pred.shape)

379/379 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
Mean Absolute Error (MAE): 240.07
Median Absolute Error (MedAE): 203.25
Mean Squared Error (MSE): 90523.77
Root Mean Squared Error (RMSE): 300.87
Mean Absolute Percentage Error (MAPE): 1.65 %
Median Absolute Percentage Error (MDAPE): 1.42 %


y_test_unscaled.shape=  (12105, 1)
y_pred.shape=  (12105, 1)


# Fine Tuning

In [58]:
checkpoints = r'C:\Users\swiss\Desktop\ML\Lab 7\E1\E2-cp-{epoch:04d}-loss{val_loss:.2f}.h5'
model= r'C:\Users\swiss\Desktop\ML\Lab 7\E1\E1-cp-0010-loss0.02.h5'
start_epoch= 11

In [59]:
EpochCheckpoint1 = ModelCheckpoint(checkpoints,
                             monitor="val_loss",
                             save_best_only=True, 
                             verbose=1)

if model is None:
    print("[INFO] compiling model...")
    model = PC.build(time_steps=24, num_features=21, reg=0.0005)
    opt = Adam(1e-3)
    model.compile(loss= 'mae', optimizer=opt, metrics=["mae", "mape"])
# otherwise, load the checkpoint from disk
else:
    print("[INFO] loading {}...".format(model))
    model = load_model(model, 
    custom_objects={'mae': MeanAbsoluteError()})

    # update the learning rate
    print("[INFO] old learning rate: {}".format(K.set_value(model.optimizer.lr)))
    K.set_value(model.optimizer.lr, 1e-4)
    print("[INFO] new learning rate: {}".format(K.set_value(model.optimizer.lr)))

[INFO] loading C:\Users\swiss\Desktop\ML\Lab 7\E1\E1-cp-0010-loss0.02.h5...


AttributeError: module 'keras.api.backend' has no attribute 'set_value'

In [37]:
epochs = 10
verbose = 1 #0
batch_size = 32
History = model.fit(train_X,
                        train_y,
                        batch_size=batch_size,   
                        epochs = epochs, 
                        validation_data = (validation_X,validation_y),
                        callbacks=callbacks,
                        verbose = verbose)

Epoch 1/10


NotImplementedError: numpy() is only available when eager execution is enabled.

In [ ]:

model = load_model(r'C:\Users\swiss\Desktop\ML\Lab 7\E1\E2-cp-0006-loss0.01.h5')

y_pred_scaled   = model.predict(test_X)
y_pred          = scaler.inverse_transform(y_pred_scaled)
y_test_unscaled = scaler.inverse_transform(test_y)
# Mean Absolute Error (MAE)
MAE = np.mean(abs(y_pred - y_test_unscaled)) 
print('Mean Absolute Error (MAE): ' + str(np.round(MAE, 2)))

# Median Absolute Error (MedAE)
MEDAE = np.median(abs(y_pred - y_test_unscaled))
print('Median Absolute Error (MedAE): ' + str(np.round(MEDAE, 2)))

# Mean Squared Error (MSE)
MSE = np.square(np.subtract(y_pred, y_test_unscaled)).mean()
print('Mean Squared Error (MSE): ' + str(np.round(MSE, 2)))

# Root Mean Squarred Error (RMSE) 
RMSE = np.sqrt(np.mean(np.square(y_pred - y_test_unscaled)))
print('Root Mean Squared Error (RMSE): ' + str(np.round(RMSE, 2)))

# Mean Absolute Percentage Error (MAPE)
MAPE = np.mean((np.abs(np.subtract(y_test_unscaled, y_pred)/ y_test_unscaled))) * 100
print('Mean Absolute Percentage Error (MAPE): ' + str(np.round(MAPE, 2)) + ' %')

# Median Absolute Percentage Error (MDAPE)
MDAPE = np.median((np.abs(np.subtract(y_test_unscaled, y_pred)/ y_test_unscaled))) * 100
print('Median Absolute Percentage Error (MDAPE): ' + str(np.round(MDAPE, 2)) + ' %')

print('\n\ny_test_unscaled.shape= ',y_test_unscaled.shape)
print('y_pred.shape= ',y_pred.shape)

379/379 [==============================] - 1s 1ms/step
Mean Absolute Error (MAE): 144.75
Median Absolute Error (MedAE): 113.65
Mean Squared Error (MSE): 36189.68
Root Mean Squared Error (RMSE): 190.24
Mean Absolute Percentage Error (MAPE): 0.98 %
Median Absolute Percentage Error (MDAPE): 0.79 %


y_test_unscaled.shape=  (12105, 1)
y_pred.shape=  (12105, 1)
